import { TbPalette } from "react-icons/tb";
import {
  HomeIcon,
  UserIcon as HiUserIcon,
  LightBulbIcon,
  DocumentTextIcon,
  ChatBubbleLeftRightIcon,
  BoltIcon,
  UsersIcon,
  CurrencyDollarIcon,
  UserCircleIcon,
  CubeIcon,
  BriefcaseIcon,
  MegaphoneIcon,
  SparklesIcon,
  NewspaperIcon,
  ChatBubbleOvalLeftIcon,
  UserGroupIcon,
  CalendarIcon,
  ShareIcon,
  ClipboardDocumentListIcon,
  AcademicCapIcon,
  BookOpenIcon,
  ChatBubbleLeftEllipsisIcon,
  CalendarDaysIcon,
  ArrowPathIcon,
  CheckBadgeIcon,
  ChatBubbleBottomCenterTextIcon,
  MapIcon,
  ScaleIcon,
  HeartIcon,
  PaperAirplaneIcon,
  FlagIcon,
  BuildingOffice2Icon,
  ClockIcon,
  ViewColumnsIcon,
  IdentificationIcon,
  FolderIcon,
  WindowIcon,
  CircleStackIcon,
  LinkIcon,
  CpuChipIcon,
  Cog6ToothIcon,
} from "@heroicons/react/24/outline";
import { ElementType } from "react";

import DashboardsIcon from "@/assets/dualicons/dashboards.svg?react";
import SettingIcon from "@/assets/dualicons/setting.svg?react";

export const navigationIcons: Record<string, ElementType> = {
  dashboards: DashboardsIcon,
  settings: SettingIcon,
  "dashboards.home": HomeIcon,
  "settings.general": HiUserIcon,
  "settings.appearance": TbPalette,

  // CEO OS
  "ceo.insights": LightBulbIcon,
  "ceo.relatorios": DocumentTextIcon,
  "ceo.conselho": ChatBubbleLeftRightIcon,
  "ceo.operacao": BoltIcon,
  "ceo.clientes": UsersIcon,
  "ceo.financeiro": CurrencyDollarIcon,
  "ceo.pessoas": UserCircleIcon,
  "ceo.produto": CubeIcon,
  "ceo.comercial": BriefcaseIcon,
  "ceo.marketing": MegaphoneIcon,
  "ceo.presenca": SparklesIcon,
  "ceo.feed": NewspaperIcon,
  "ceo.chat": ChatBubbleOvalLeftIcon,
  "ceo.comunidades": UserGroupIcon,
  "ceo.eventos": CalendarIcon,
  "ceo.organograma": ShareIcon,
  "ceo.pesquisas": ClipboardDocumentListIcon,
  "ceo.universidade": AcademicCapIcon,
  "ceo.treinamentos": BookOpenIcon,
  "ceo.equipe": UserGroupIcon,
  "ceo.1on1": ChatBubbleLeftEllipsisIcon,
  "ceo.agendamento": CalendarDaysIcon,
  "ceo.autoavaliacao": UserCircleIcon,
  "ceo.av360": ArrowPathIcon,
  "ceo.avgestor": CheckBadgeIcon,
  "ceo.feedback": ChatBubbleBottomCenterTextIcon,
  "ceo.pdi": MapIcon,
  "ceo.calibracao": ScaleIcon,
  "ceo.recebidos": HeartIcon,
  "ceo.enviados": PaperAirplaneIcon,
  "ceo.metas": FlagIcon,
  "ceo.corporativa": BuildingOffice2Icon,
  "ceo.area": UserGroupIcon,
  "ceo.individual": HiUserIcon,
  "ceo.horas": ClockIcon,
  "ceo.organizacao": ViewColumnsIcon,
  "ceo.vagas": BriefcaseIcon,
  "ceo.candidatos": IdentificationIcon,
  "ceo.cvs": FolderIcon,
  "ceo.whatsapp": ChatBubbleLeftRightIcon,
  "ceo.divulgacao": WindowIcon,
  "ceo.campanhas": MegaphoneIcon,
  "ceo.memoria": CircleStackIcon,
  "ceo.conectores": LinkIcon,
  "ceo.agentes": CpuChipIcon,
  "ceo.config": Cog6ToothIcon,
};
